# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy schedule

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
        sudo apt-get install -y libreoffice-core libreoffice-calc xmlstarlet

    - name: Convert Excel-Sheet to XML-Frab format
      run: |
        poetry run ./convert.sh
        cat *csv

    - name: Validate XML
      run: |
        wget https://raw.githubusercontent.com/voc/schedule/master/validator/xsd/schedule.xml.xsd
        xmlstarlet val -s schedule.xml.xsd schedule-ita.xml

    - name: Commit schedule
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'github-action@users.noreply.github.com'
        git commit -am "Generated schedule"
        git push
